# Generated by Django 5.1.2 on 2024-10-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('professor', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
