# Generated by Django 5.1.2 on 2024-10-15 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('professor', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StackCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='course',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stack_courses', to='cursos.stackcourse'),
        ),
    ]
