# Generated by Django 5.1.2 on 2024-10-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_course_stackcourse_delete_curso_course_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_link',
            field=models.CharField(default='No-image', max_length=200),
        ),
    ]
